name: Semgrep SCA Pipeline Lockfileless

on:
  workflow_dispatch:
  pull_request:

jobs:
  semgrep-the-sca:
    runs-on: ubuntu-latest
    container: semgrep/semgrep:1.144.0
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep SCA Lockfileless
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: |
          ls -lah
          tree
          semgrep ci --supply-chain --allow-local-builds --include=build.sbt --verbose --json --output=report-ssc.json || true
          semgrep ci --supply-chain --json --output=report-ssc.json --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: report-ssc.json
